---
title: "Denoising paper"
author: "Dimitri Fichou"
date: "March 3, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,dev="png",dpi=300,fig.path = "../figures/")
library(DLC)
```


```{r unit_view_2-prep,cache=T,echo=F,warning=F,message=F,autodep = TRUE}
conv <- 2
hidden <- 16
numepochs <- 50
batchsize <- 1000
learningrate <- 0.1
momentum <- 0.5
cd <- 2
set.seed(1)
data <- DLC::f.read.image("../data/bioassay-1.jpg",height = 256,Normalize=T)
decon <- data %>% deconstruct.convol(margin = 3,transform = F,conv_width = conv)
model <- rbm.train(decon,hidden = hidden,numepochs = numepochs,batchsize = batchsize,learningrate = learningrate,momentum = momentum,cd = cd,verbose = T)
up <- decon %>% rbm.up(model,.)
ups <- up %>% reconstruct(margin=3,transform = F,dimension = dim(data))
down <-  up %>% rbm.down(model,.)
recon <- down %>% reconstruct.convol(margin=3,transform = F,dimension = dim(data),conv_width = conv,take_center = F)
```







```{r Denoising_Fig_4,fig.height=1.75,fig.width=7, cache=T,echo=F,warning=F,message=F}
par(xaxt="n",yaxt="n",bty="o",oma=c(0,0.1,0,0.1)) 
layout(rbind(c(39,1:19), c(40,20:38)))

par(mar=c(0,0,2,0))
data[(dim(data)[1]-75):(dim(data)[1]-95),470:500,] %>% raster(main="O")
segments(x0=15,x1=15,y0=20,y1=0,col="red",lty=2)

# Normalize zoom unit views
for(i in seq(hidden)){
  ups[(dim(data)[1]-75):(dim(data)[1]-95),470:500,i] %>% normalize %>% raster(main=i)
  # abline(v=15,col="red",lwd=0.5)
  segments(x0=15,x1=15,y0=20,y1=0,col="red",lty=2)
  }



recon[(dim(data)[1]-75):(dim(data)[1]-95),470:500,] %>% raster(main="R")
# arrows(x0=15,x1=15,y0=5,y1=0,length = 0.05,col="red")
segments(x0=15,x1=15,y0=20,y1=0,col="red",lty=2)

EBImage::medianFilter(data,3)[(dim(data)[1]-75):(dim(data)[1]-95),470:500,] %>% raster(main="M")
segments(x0=15,x1=15,y0=20,y1=0,col="red",lty=2)


par(mar=c(0,0,0,0))

for(i in seq(3)){
  plot(x=apply(data[(dim(data)[1]-95):(dim(data)[1]-75),470:500,i],1,mean),y=75:95,
       type="l",col=c("red","green","blue")[i])
  par(new=T)
}
abline(h=c(80,85,90),lty=2)
par(new=F)

# Peak zoom
for(i in seq(hidden)){
  plot(x=apply(ups[(dim(data)[1]-95):(dim(data)[1]-75),470:500,i],1,mean),y=75:95,type="l")
  # plot(x=ups[(dim(data)[1]-95):(dim(data)[1]-75),485,i],y=75:95,type="l")
  abline(h=c(80,85,90),lty=2)
}

for(i in seq(3)){
  plot(x=apply(recon[(dim(data)[1]-95):(dim(data)[1]-75),470:500,i],1,mean),y=75:95,
       type="l",col=c("red","green","blue")[i])
  par(new=T)
}
par(new=F)
abline(h=c(80,85,90),lty=2)

for(i in seq(3)){
  plot(x=apply(EBImage::medianFilter(data,3)[(dim(data)[1]-95):(dim(data)[1]-75),470:500,i],1,mean),y=75:95,
       type="l",col=c("red","green","blue")[i])
  par(new=T)
}
abline(h=c(80,85,90),lty=2)
par(new=F)

par(mar=c(0,0,2,0))
plot(x=1,y=1,type="n",bty="n")
text(x=1,y=1,labels="A",cex=1.5)
par(mar=c(0,0,0,0))
plot(x=1,y=1,type="n",bty="n")
text(x=1,y=1,labels="B",cex=1.5)

```