---
title: "rTLC paper TOC"
author: "Fichou D."
date: "`r Sys.Date()`"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: pdflatex
  html_document:
    fig_caption: yes
  word_document:
    fig_caption: yes
    fig_height: 5
    fig_width: 5
---


```{r setup, include=FALSE,echo=F,warning=F,message=F}
knitr::opts_chunk$set(dpi=300, cache=T,echo=F,warning=F,message=F,autodep=T,eval=T,fig.path ="../figures/")
library(DLC)


```




```{r rtlc_TOC,fig.height=1.875,fig.width=3.33,dpi=300, cache=T,echo=F,warning=F,message=F,eval=T,dev=c("png")}
data = DLC::f.read.image(dir("../data/",pattern = "propolis-silicate-",full.names = T),height = 126,ls.format = T)
par(mar=c(0,0,0,0),xaxt="n",yaxt="n",bty="n", xaxs="i", yaxs="i")
par(bg = "white")

plot(c(0,6),c(0,6.75),type="n")

for(i in 2:7){
  rasterImage(data[[i]],0,i-2,2,i-1)
}

# text(x=c(1),y=c(5.75),labels=c("Input data"),cex=0.75,pos=3)

raster_logo=function(source,position,size){
  logo = readPNG(source)
  rasterImage(logo,
              position[1]-size[1]/2,position[2]-size[2]/2,
              position[1]+size[1]/2,position[2]+size[2]/2)
}

# text(x=2,y=3,pos=4,labels = "rTLC",cex=1.5)
arrows(x0 = 2.1,x1=c(3.9),y0 = c(3),y1=c(3),length = 0.1)

# raster_logo("Screenshot trackPlot.png",c(5.2,5.2),0.0027)

text(x=c(3),y=c(3),labels=c("rTLC"),pos=3,cex=1)
text(x=c(3),y=c(3),labels=c("open-source\nfast\nall-in-one"),pos=1,cex=0.75)

raster_logo("../data/Screenshot PCA.png",c(5,5),c(2,2))
raster_logo("../data/Screenshot HCA.png",c(5,3),c(2,2))
raster_logo("../data/Screenshot Regression.png",c(5,1),c(2,2))



# text(x=c(5),y=c(5.75),labels=c("Analysed data"),cex=0.75,pos=3)
```
